# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3eb84d988dbedb17b4f4051be16914fbfa84999e936e19989770671863682093dbb2d3d0c1d7f7039d69f08e7d33a3ab4082c897149a1a467e7f46765950fc4

staging:
  secret_key_base: 480f405383c01961cab887ec0e2cbcf22e81718bd0b5b8417fe1b09272e2bd19aac5bb5a759092614479c3a567fca3ee4929d56bd65747dbcd45d13bc4e349fa

test:
  secret_key_base: f4b2dc2e55add3b7162664aa9affd6b745f4a8a13edbfaf8c8a49ff1fb7590c2c6e083cf4f0027c1034bb4bc60956985b5ee8290d305e4bd3546ceb8863a8a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
