class AddDetailsToOrderForms < ActiveRecord::Migration
  def change
    add_column :order_forms, :orthotic_profile, :string
    add_column :order_forms, :shell_material, :string
    add_column :order_forms, :shell_modifications_fill_arch_left, :boolean
    add_column :order_forms, :shell_modifications_fill_arch_right, :boolean
    add_column :order_forms, :shell_modifications_first_met_cutout_left, :boolean
    add_column :order_forms, :shell_modifications_first_met_cutout_right, :boolean
    add_column :order_forms, :shell_modifications_first_ray_cutout_left, :boolean
    add_column :order_forms, :shell_modifications_first_ray_cutout_right, :boolean
    add_column :order_forms, :shell_modifications_flange_lat_med_left, :boolean
    add_column :order_forms, :shell_modifications_flange_lat_med_right, :boolean
    add_column :order_forms, :shell_modifications_gate_plate_in_out_left, :boolean
    add_column :order_forms, :shell_modifications_gate_plate_in_out_right, :boolean
    add_column :order_forms, :shell_modifications_heel_spur_hole_left, :boolean
    add_column :order_forms, :shell_modifications_heel_spur_hole_right, :boolean
    add_column :order_forms, :post_heel, :string
    add_column :order_forms, :post_heel_right_medial, :string
    add_column :order_forms, :post_heel_left_medial, :string
    add_column :order_forms, :post_heel_right_lateral, :string
    add_column :order_forms, :post_heel_left_lateral, :string
    add_column :order_forms, :post_forefoot, :string
    add_column :order_forms, :post_forefoot_right_medial, :string
    add_column :order_forms, :post_forefoot_left_medial, :string
    add_column :order_forms, :post_forefoot_right_lateral, :string
    add_column :order_forms, :post_forefoot_left_lateral, :string
    add_column :order_forms, :shell_width, :string
    add_column :order_forms, :heel_cup, :string
    add_column :order_forms, :heel_lift_left, :string
    add_column :order_forms, :heel_lift_right, :string
    add_column :order_forms, :pronation_skive_heel_post_left_corner_skive_only, :boolean
    add_column :order_forms, :pronation_skive_heel_post_right_corner_skive_only, :boolean
    add_column :order_forms, :pronation_skive_heel_post_left_skive_1_3_medial_post_surface, :boolean
    add_column :order_forms, :pronation_skive_heel_post_right_skive_1_3_medial_post_surface, :boolean
    add_column :order_forms, :kirby_skive_left, :string
    add_column :order_forms, :kirby_skive_right, :string
    add_column :order_forms, :cover_length, :string
    add_column :order_forms, :top_cover, :string
    add_column :order_forms, :cushion, :string
    add_column :order_forms, :forefoot_cushion_left, :string
    add_column :order_forms, :forefoot_cushion_right, :string
    add_column :order_forms, :metatarsal_pads_left_thickness, :string
    add_column :order_forms, :metatarsal_pads_right_thickness, :string
    add_column :order_forms, :metatarsal_pads_left_density, :string
    add_column :order_forms, :metatarsal_pads_right_density, :string
    add_column :order_forms, :met_pad_width, :string
    add_column :order_forms, :heel_padding_left_style, :string
    add_column :order_forms, :heel_padding_right_style, :string
    add_column :order_forms, :heel_padding_left_extended, :string
    add_column :order_forms, :heel_padding_right_extended, :string
    add_column :order_forms, :digit_cutout_left, :integer
    add_column :order_forms, :digit_cutout_right, :integer
    add_column :order_forms, :cutout_w_u_left, :integer
    add_column :order_forms, :cutout_w_u_right, :integer
    add_column :order_forms, :navicular_relief_left, :boolean
    add_column :order_forms, :navicular_relief_right, :boolean
    add_column :order_forms, :specialties_mortons_extension_left, :boolean
    add_column :order_forms, :specialties_mortons_extension_right, :boolean
    add_column :order_forms, :specialties_reverse_mortons_left, :boolean
    add_column :order_forms, :specialties_reverse_mortons_right, :boolean
    add_column :order_forms, :specialties_tendon_relief_track_left, :boolean
    add_column :order_forms, :specialties_tendon_relief_track_right, :boolean
    add_column :order_forms, :svl_file, :string
    add_column :order_forms, :csv_file, :string
  end
end
